<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Robotic_Arm">

<xacro:property name="stepper_box_length" value="0.05"/>
<xacro:property name="stepper_box_width" value="0.05"/>
<xacro:property name="stepper_box_height" value="0.05"/>
<xacro:property name="L1_arm_length" value="0.3"/>
<xacro:property name="L1_arm_radius" value="0.025"/>
<xacro:property name="L2_arm_length" value="0.3"/>
<xacro:property name="L2_arm_radius" value="0.025"/>


    <link name="world_link">
    </link>
    <link name="base_link">
    <visual>
        <geometry>
            <cylinder radius="0.10" length="0.1"/>
        </geometry>
    </visual>
    </link>
    <joint name="world_to_base_joint" type="fixed">
        <parent link="world_link"/>
        <child link="base_link"/>
    </joint>
    <link name="upper_base_link">
        <visual>
            <geometry>
                <cylinder radius="0.10" length="0.01"/>
            </geometry>
        </visual>
    </link>
    <joint name="base_to_upper_base" type="continuous">
        <parent link="base_link"/>
        <child link="upper_base_link"/>
        <origin xyz="0.0 0.0 0.06" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
        
    </joint>
    <link name="base_stepper_link">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
    </link>
    <joint name="upper_base_to_base_stepper" type="fixed">
        <parent link="upper_base_link"/>
        <child link="base_stepper_link"/>
        <origin xyz="-0.056 0.0 ${stepper_box_height/2}" rpy="0.0 0.0 0.0"/>
        
    </joint>
    <link name="L1_link">
        <visual>
            <geometry>
                <cylinder radius="${L1_arm_radius}" length="${L1_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${L1_arm_length/2}" rpy="0.0 0.0 0.0"/>
            
        </visual>
    </link>
    <joint name="base_stepper_to_L1_joint" type="revolute">
        <parent link="base_stepper_link"/>
        <child link="L1_link"/>
        <origin xyz="0.05 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="1.0 0.0 0.0"/>
        <limit lower="-1.57" upper="1.57" effort="9.8" velocity="2.0"/>
        
    </joint>
    <link name="upper_stepper_link">
        <visual>
        <geometry>
            <box size="${stepper_box_length} ${stepper_box_width} ${stepper_box_height}"/>
        </geometry>
        </visual>
    </link>
    <joint name="joint_name" type="fixed">
        <parent link="L1_link"/>
        <child link="upper_stepper_link"/>
        <origin xyz="0.0 0.0 ${L1_arm_length + stepper_box_height/2}" rpy="0.0 0.0 0.0"/>
    </joint>
    <link name="L2_link">
        <visual>
            <geometry>
                <cylinder radius="${L2_arm_radius}" length="${L2_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${L2_arm_length/2}" rpy="0.0 0.0 0.0"/>
            
        </visual>
    </link>
    <joint name="upper_stepper_to_L2_joint" type="continuous">
        <parent link="upper_stepper_link"/>
        <child link="L2_link"/>
        <origin xyz="${stepper_box_length/2 + L2_arm_radius} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="1.0 0.0 0.0"/>
    </joint>

</robot>